### ISSUE TITLE
App won't start: Current must not be NaN

### ISSUE THREAD

**Issue by themrvideouser** [RLD-JL/Just-Listen#17]
I've upgraded today from 1.0.6 to 1.0.8: current must not be NaN, tried 1.0.7-c: same error, tried 1.0.6-b: works 
Android 14 on Pixel 8 with latest stable GrapheneOS 20240929
Crash Report:
```
type: crash
osVersion: google/shiba/shiba:14/AP2A.240905.003/2024092900:user/release-keys
package: com.rld.justlisten.android:23
process: com.rld.justlisten.android
processUptime: 284 + 229 ms
installer: com.android.packageinstaller

java.lang.IllegalArgumentException: current must not be NaN
	at r0.f.<init>(SourceFile:1)
	at s.O0.h(SourceFile:30)
	at r0.c.W(SourceFile:1)
	at s.U.a(SourceFile:604)
	at s.U.n(SourceFile:144)
	at I.j.c(SourceFile:65)
	at R.z.a(SourceFile:60)
	at android.support.v4.media.u.e(SourceFile:73)
	at androidx.compose.ui.node.a.l(SourceFile:48)
	at N5.B.f(SourceFile:120)
	at r0.p.b(SourceFile:34)
	at r0.p.b(SourceFile:42)
	at r0.p.l(SourceFile:15)
	at r0.p.g(SourceFile:27)
	at androidx.compose.ui.platform.H.N(SourceFile:93)
	at androidx.compose.ui.platform.H.M(SourceFile:30)
	at androidx.compose.ui.platform.H.N(SourceFile:83)
	at androidx.compose.ui.platform.H.M(SourceFile:30)
	at androidx.compose.ui.platform.H.N(SourceFile:83)
	at androidx.compose.ui.platform.H.M(SourceFile:30)
	at androidx.compose.ui.platform.H.N(SourceFile:83)
	at androidx.compose.ui.platform.H.M(SourceFile:30)
	at androidx.compose.ui.platform.H.N(SourceFile:83)
	at androidx.compose.ui.platform.H.N(SourceFile:109)
	at androidx.compose.ui.platform.H.M(SourceFile:30)
	at androidx.compose.ui.platform.H.q(SourceFile:134)
	at androidx.compose.ui.platform.H.m(SourceFile:35)
	at androidx.compose.ui.platform.H.G(SourceFile:12)
	at androidx.compose.ui.platform.H.H(SourceFile:1)
	at androidx.compose.ui.platform.H.K(SourceFile:86)
	at androidx.compose.ui.platform.H.k(SourceFile:147)
	at androidx.compose.ui.platform.i1.i(SourceFile:35)
	at y5.a.p(SourceFile:1)
	at N5.I.run(SourceFile:1)
	at androidx.compose.ui.platform.U.l0(SourceFile:7)
	at androidx.compose.ui.platform.T.run(SourceFile:3)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: S5.g: [androidx.compose.ui.platform.y0@1a90912, I.e@ba888e3, s0{Cancelling}@309a2e0, U@3fac999]
```

**Comment by RLD-JL** [comment]
Should be fixed now, please, let me know if it still persists
